# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'NewsFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for NewsFeed

  target 'NewsFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsFeedUITests' do
    # Pods for testing
  end

end
